# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "trusty64"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    config.vm.network :public_network

    # compiling GCC needs more memory
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "768"]
      v.customize ["modifyvm", :id, "--cpus", 2]
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "sentry.yml"
    end
end